### ISSUE TITLE
Issue setting up gateway server on Windows

### ISSUE THREAD

**Issue by wolberine** [magic-network/magic-agent#13]
After I install Docker and do `docker-compose up` I receive the following error: 

`Starting magic-agent_magic-gateway_1 ... done
Attaching to magic-agent_magic-gateway_1
magic-gateway_1  | [FATAL tini (6)] exec /run.sh failed: No such file or directory
magic-agent_magic-gateway_1 exited with code 127`

Thanks team!

**Comment by cslamar** [comment]
When building on a Windows machine, you need to ensure that your files have Unix style newlines.  By default Windows uses CRLF newlines.  If you edit a file on Windows, make sure that your editor is set to use Unix style newlines.

**Comment by magicpia** [comment]
Hey @rbalik! @cslamar Mentioned you have settings for your Git config to force everything to be Unix line endings on your Windows laptop. Mind posting here for the community?

**Comment by rbalik** [comment]
So it was an option when running the git installer the first time but I think you can change with the git config command:
`git config --global core.autocrlf false`

That will make it so no adjustments are made to line endings and whatever is in the repo will match what you get.
