### ISSUE TITLE
Depdency on Docker limits Windows 10 Home Users

### ISSUE THREAD

**Issue by sbehrens** [magic-network/magic-agent#3]
Hi Team,

I'm a Windows 10 home user, but Docker/Docker-Compose aren't supported on the platform.  Consider an alternative method to shipping the code or updating the docs to specify Windows 10 Enterprise/Pro required.

Thanks,
Scott

**Comment by magicpia** [comment]
Hey @sbehrens we've gone ahead an included this on our [documentation page ](https://magic-network.github.io/magic-agent/provider/gateway/quick-start/hardware-prereqs.html)

Thanks!
